import os, psycopg2
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# Complete PostgreSQL schema for AI Fall Detection System
# Run this script once to create/update all tables in Neon DB.
# Uses IF NOT EXISTS so it's safe to run multiple times.
# ─────────────────────────────────────────────────────────────────────────────

SQL = """
-- ── Users ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(150) UNIQUE NOT NULL,
    mobile          VARCHAR(20)  DEFAULT '',
    password_hash   VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── Detection Logs ──────────────────────────────────────────────────────────
-- source: 'mock' | 'live_camera' | 'video' | 'websocket'
CREATE TABLE IF NOT EXISTS detection_logs (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER REFERENCES users(id) ON DELETE CASCADE,
    type        VARCHAR(20)  NOT NULL,        -- FALL | NORMAL | NO_PERSON
    confidence  FLOAT        DEFAULT 0,
    source      VARCHAR(30)  DEFAULT 'mock',  -- 30 chars to allow 'live_camera' etc.
    timestamp   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── Analysis Reports ────────────────────────────────────────────────────────
-- Stores metadata for CSV reports generated by video analysis.
CREATE TABLE IF NOT EXISTS reports (
    id             SERIAL PRIMARY KEY,
    user_id        INTEGER REFERENCES users(id) ON DELETE CASCADE,
    file_name      VARCHAR(255) NOT NULL,
    file_uri       TEXT,                      -- Path to CSV on server
    fall_detected  BOOLEAN      DEFAULT FALSE,
    confidence     FLOAT        DEFAULT 0,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ── User Settings ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_settings (
    id              SERIAL  PRIMARY KEY,
    user_id         INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    voice_alerts    BOOLEAN DEFAULT TRUE,
    alert_cooldown  INTEGER DEFAULT 15,
    mode            VARCHAR(20) DEFAULT 'simulation', -- 'simulation' | 'live'
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── Safe ALTER statements (add columns that may be missing in existing DBs) ──
DO $$
BEGIN
    -- Extend source column to 30 chars if it was created as VARCHAR(20)
    BEGIN
        ALTER TABLE detection_logs ALTER COLUMN source TYPE VARCHAR(30);
    EXCEPTION WHEN others THEN NULL;
    END;

    -- Add mobile column if missing (old schema had it nullable)
    BEGIN
        ALTER TABLE users ALTER COLUMN mobile SET DEFAULT '';
    EXCEPTION WHEN others THEN NULL;
    END;
END$$;
"""

try:
    print("[...] Connecting to Neon PostgreSQL...")
    conn = psycopg2.connect(os.getenv("DATABASE_URL"))
    cur = conn.cursor()
    cur.execute(SQL)
    conn.commit()

    # Verify all tables exist
    cur.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """)
    tables = [row[0] for row in cur.fetchall()]
    conn.close()

    print("[OK] All tables created/verified in Neon DB!")
    print(f"[OK] Tables found: {', '.join(tables)}")

except Exception as e:
    print(f"[ERROR] Database setup failed: {e}")
    raise
